on:
  push:
  schedule:
    - cron: '0 0 */1 * *'

name: Docker Registry Test

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - run: docker version
      - run: docker info
      - name: Docker Registry Test
        run: |
          registrys="
          ${ALIYUN_MIRROR}.mirror.aliyuncs.com
          daocloud.io
          mirror.baidubce.com
          reg.qiniu.com
          docker.mirrors.ustc.edu.cn
          registry.docker-cn.com
          dockerhub.azk8s.cn
          "
          image="library/nginx:1.18"
          for registry in $registrys
          do
             docker pull $registry/$image \
               && (echo -e "\033[32m$registry is good\033[0m" \
                  ; echo "::info file=README.md,line=1,col=0::OK [ $registry ] is good") \
               || (echo -e "\033[31m$registry is outdated\033[0m" \
                  ; echo "::error file=README.md,line=1,col=0::X [ $registry ] is outdated")
             docker rmi $registry/$image || true
          done
        env:
          ALIYUN_MIRROR: ${{secrets.ALIYUN_MIRROR}}
